In [1]:
import tensorflow as tf

In [2]:
import numpy as np
W = np.loadtxt('/content/W.csv',delimiter=',')
hb = np.loadtxt('/content/hb.csv',delimiter=',')
vb = np.loadtxt('/content/vb.csv',delimiter=',')
#trX = np.loadtxt('/content/trX.csv',delimiter=',')

In [3]:
W = tf.convert_to_tensor(W, dtype=tf.float32)
hb = tf.convert_to_tensor(hb, dtype=tf.float32)
vb = tf.convert_to_tensor(vb, dtype=tf.float32)

In [4]:
#Tensorflow library. Used to implement machine learning models
import tensorflow as tf
#Numpy contains helpful functions for efficient mathematical calculations
import numpy as np
#Dataframe manipulation library
import pandas as pd
#Graph plotting library
import matplotlib.pyplot as plt
%matplotlib inline

In [62]:
products_df = pd.read_csv('/content/productsT.csv', sep=',', header=None, engine='python')
ratings_df = pd.read_csv('/content/ratingsT.csv', sep=',', header=None, engine='python')
products_df.columns = ['ProductID', 'Title', 'Tags']
ratings_df.columns = ['UserID', 'ProductID', 'Rating']


user_rating_df = ratings_df.pivot_table(index='UserID', columns='ProductID', values='Rating')
norm_user_rating_df = user_rating_df.fillna(0) / 5.0
trX = norm_user_rating_df.values
trX[0:5]

array([[0.        , 0.56      , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.32      , 0.        ,
        0.06      , 0.        , 0.60666667, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.53      , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.1       , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.36      , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.54      , 0.        , 0.        , 0.76      ,
        0.        , 0.        , 0.        , 0.    

In [63]:
import pandas as pd 
df = pd.read_csv('/content/trX.csv', sep=',')

In [64]:
trX=df.values

In [65]:
trX

array([[0.        , 0.56      , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.32      , 0.        ,
        0.06      , 0.        , 0.60666667, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.53      , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.1       , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.36      , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.54      , 0.        , 0.        , 0.76      ,
        0.        , 0.        , 0.        , 0.    

In [66]:
mock_user_id = 1

In [67]:
#Selecting the input user

inputUser = trX[mock_user_id-1].reshape(1, -1)
inputUser = tf.convert_to_tensor(trX[mock_user_id-1],"float32")
v0 = inputUser

In [68]:
#Feeding in the user and reconstructing the input

hh0 = tf.nn.sigmoid(tf.matmul([v0], W) + hb)
vv1 = tf.nn.sigmoid(tf.matmul(hh0, tf.transpose(W)) + vb)
rec = vv1
tf.maximum(rec,1)

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
      dtype=float32)>

In [70]:
scored_products_df_mock = products_df[products_df['ProductID'].isin(user_rating_df.columns)]
scored_products_df_mock = scored_products_df_mock.assign(RecommendationScore = rec[0])
scored_products_df_mock.sort_values(["RecommendationScore"], ascending=False).head(5)

ProductID  ... RecommendationScore
17         18  ...            0.302694
14         15  ...            0.196759
1           2  ...            0.194262
16         17  ...            0.114166
6           7  ...            0.107959

[5 rows x 4 columns]

In [ ]:
df = pd.DataFrame(scored_products_df_mock.sort_values(["RecommendationScore"], ascending=False).head(10)['ProductID'])

In [ ]:
import json
jsonObject = json.loads(df.to_json(orient='values'))


In [ ]:
listExample=[]
for i in jsonObject:
    for number in i:
        listExample.append(number)

In [ ]:
listExample

[15, 18, 2, 28, 5, 16, 26, 20, 3, 11]